cmp <- read.csv("./pre-post-tests.csv", sep=";", dec=",")
boxplot(nlex ~ TEST, data = cmp, xlab="Test 1", ylab = "Lexical accuracy" )
boxplot(ngram ~ TEST, data = cmp, xlab="Test 2", ylab = "Grammatical accuracy")
boxplot(nwriting ~ TEST, data = cmp, xlab="Test 3", ylab = "Writing skills")
boxplot(overall ~ TEST, data = cmp, xlab="Tests 1-3", ylab = "Overall grade")
